/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2018-02-21 20:41:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myjsp1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


		//Declarative tag
		float pi=3.14F;
		
		int squareOfNum(int num){
			return (num * num);
		}
		
		
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("This is HTML\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t<p>This is a Paragraph</p>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t <h3>This is heading3</h3>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\tScriptlet\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t");

		//Scriptlet is a tag to write the Java code
		
			int num=5;
			int a =20;
			int b=20;
			int c=a+b;
			
			for (int i=1;i<=10;i++){
				out.print(num+"  " + i+"'s are  " +(num*i) + "<br/>");
			}
			
			out.print("Sum is   " + c);//out is a reference fr PrintWriter object of response. *(Implicit object)
		
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tDeclarative example\r\n");
      out.write("\t\t");

		out.println("Pi is :" + pi +"<br/>" );
		out.println("Square of 5 is " + squareOfNum(5) +"<br/>");
		 
      out.write("\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tExpression example\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tpi is : ");
      out.print( pi );
      out.write("\t\t\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\tSquare of 7 is : ");
      out.print( squareOfNum(7) );
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
